spring:
  datasource:
    url: jdbc:h2:mem:propertytrees;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: true
    database: H2
    properties:
      hibernate.format_sql: true
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: /var/propertytrees/lucene/indexes/
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    com.propertiestree: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: '%d{dd-MMM-yyyy HH:mm:ss} %5p %c{1}:%L - %m%n'
image:
  upload:
    targetDir: D:\\PHOTO\\SERVER\\
allowedOrigins:
  urls: http://localhost:4200   